# Generated by Django 5.0.6 on 2024-06-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_productocarrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='productocarrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='productocarrito',
            name='precioEuro',
            field=models.FloatField(default=0.0),
        ),
    ]
