# Generated by Django 5.0.6 on 2024-06-30 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_usuarios_delete_productocarrito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoUsuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Dona')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Dona')),
                ('precio', models.IntegerField(null=True, verbose_name='Precio Dona')),
                ('precioEuro', models.FloatField(default='0.0', verbose_name='Precio Euro')),
                ('srcImagen', models.CharField(default='Imagen', max_length=400, verbose_name='Imagen')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria', verbose_name='Tipo de dona')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nombre Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
