# Generated by Django 5.0.6 on 2024-07-02 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_venta_detalleventa_delete_productousuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='usario',
            new_name='usuario',
        ),
    ]
