# Generated by Django 5.0.6 on 2024-07-15 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_rename_usario_venta_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
    ]
